#namespace("user")
#include("user.sql")
#end
#namespace("shop")
#include("shop.sql")
#end
#namespace("good")
#include("good.sql")
#end
#namespace("order")
#include("order.sql")
#end
#namespace("shopcar")
#include("shopcar.sql")
#end
