package cn.ssdut153.shop.common.model;

import cn.ssdut153.shop.common.model.base.BaseEmail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Email extends BaseEmail<Email> {

}
