package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Address extends BaseAddress<Address> {

}
