package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseAddress;
import cn.enbug.shop.common.safe.JsoupFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Address extends BaseAddress<Address> {

    @Override
    protected void filter(int filterBy) {
        JsoupFilter.filterAddress(this);
    }

}
