package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {

}
