package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseComment;
import cn.enbug.shop.common.safe.JsoupFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {

    @Override
    protected void filter(int filterBy) {
        JsoupFilter.filterComment(this);
    }

}
