package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {

}
