package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseGood;
import cn.enbug.shop.common.safe.JsoupFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Good extends BaseGood<Good> {

    @Override
    protected void filter(int filterBy) {
        JsoupFilter.filterGood(this);
    }

}
