package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseOrderNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderNumber extends BaseOrderNumber<OrderNumber> {
	
}
