package cn.enbug.shop.common.model;

import cn.enbug.shop.common.model.base.BaseShopCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopCar extends BaseShopCar<ShopCar> {

}
