package cn.ssdut153.shop.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEmail<M extends BaseEmail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setActivityCode(java.lang.String activityCode) {
		set("activity_code", activityCode);
		return (M)this;
	}

	public java.lang.String getActivityCode() {
		return get("activity_code");
	}

	public M setBindingTime(java.util.Date bindingTime) {
		set("binding_time", bindingTime);
		return (M)this;
	}

	public java.util.Date getBindingTime() {
		return get("binding_time");
	}

}
