package cn.enbug.shop.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Integer getUserId() {
        return get("user_id");
    }

    public M setUserId(java.lang.Integer userId) {
        set("user_id", userId);
        return (M) this;
    }

    public java.lang.String getReciverName() {
        return get("reciver_name");
    }

    public M setReciverName(java.lang.String reciverName) {
        set("reciver_name", reciverName);
        return (M) this;
    }

    public java.lang.String getPhoneNumber() {
        return get("phone_number");
    }

    public M setPhoneNumber(java.lang.String phoneNumber) {
        set("phone_number", phoneNumber);
        return (M) this;
    }

    public java.lang.String getAddress() {
        return get("address");
    }

    public M setAddress(java.lang.String address) {
        set("address", address);
        return (M) this;
    }

    public java.lang.Integer getIsDefault() {
        return get("is_default");
    }

    public M setIsDefault(java.lang.Integer isDefault) {
        set("is_default", isDefault);
        return (M) this;
    }

}
