package cn.enbug.shop.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopCar<M extends BaseShopCar<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Integer getShopId() {
        return get("shop_id");
    }

    public M setShopId(java.lang.Integer shopId) {
        set("shop_id", shopId);
        return (M) this;
    }

    public java.lang.Integer getGoodId() {
        return get("good_id");
    }

    public M setGoodId(java.lang.Integer goodId) {
        set("good_id", goodId);
        return (M) this;
    }

    public java.lang.Integer getUserId() {
        return get("user_id");
    }

    public M setUserId(java.lang.Integer userId) {
        set("user_id", userId);
        return (M) this;
    }

    public java.lang.Integer getCount() {
        return get("count");
    }

    public M setCount(java.lang.Integer count) {
        set("count", count);
        return (M) this;
    }

    public java.lang.String getAvator() {
        return get("avator");
    }

    public M setAvator(java.lang.String avator) {
        set("avator", avator);
        return (M) this;
    }

    public java.lang.String getGoodUuid() {
        return get("good_uuid");
    }

    public M setGoodUuid(java.lang.String goodUuid) {
        set("good_uuid", goodUuid);
        return (M) this;
    }

    public java.lang.String getShopUuid() {
        return get("shop_uuid");
    }

    public M setShopUuid(java.lang.String shopUuid) {
        set("shop_uuid", shopUuid);
        return (M) this;
    }

}
