package cn.enbug.shop.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShop<M extends BaseShop<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.String getShopName() {
        return get("shop_name");
    }

    public M setShopName(java.lang.String shopName) {
        set("shop_name", shopName);
        return (M) this;
    }

    public java.lang.String getUuid() {
        return get("uuid");
    }

    public M setUuid(java.lang.String uuid) {
        set("uuid", uuid);
        return (M) this;
    }

    public java.lang.String getDescription() {
        return get("description");
    }

    public M setDescription(java.lang.String description) {
        set("description", description);
        return (M) this;
    }

    public java.lang.Integer getOwnerUserId() {
        return get("owner_user_id");
    }

    public M setOwnerUserId(java.lang.Integer ownerUserId) {
        set("owner_user_id", ownerUserId);
        return (M) this;
    }

    public java.lang.Integer getAvator() {
        return get("avator");
    }

    public M setAvator(java.lang.Integer avator) {
        set("avator", avator);
        return (M) this;
    }

}
