package cn.enbug.shop.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderNumber<M extends BaseOrderNumber<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.String getOrderNumber() {
        return get("order_number");
    }

    public M setOrderNumber(java.lang.String orderNumber) {
        set("order_number", orderNumber);
        return (M) this;
    }

    public java.lang.Integer getUserId() {
        return get("user_id");
    }

    public M setUserId(java.lang.Integer userId) {
        set("user_id", userId);
        return (M) this;
    }

    public java.lang.Integer getStatus() {
        return get("status");
    }

    public M setStatus(java.lang.Integer status) {
        set("status", status);
        return (M) this;
    }

}
